name: mongo-sharding

services:
  # Config Server (1 нода)
  config_server:
    container_name: config_server
    restart: always
    image: dh-mirror.gitverse.ru/mongo:latest
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    ports:
      - "27017:27017"
    volumes:
      - config_server_data:/data/configdb
    networks:
      - mongo_cluster

  # Шард 1
  mongodb1:
    container_name: mongodb1
    restart: always
    ports:
      - "27018:27018"
    image: dh-mirror.gitverse.ru/mongo:latest
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    volumes:
      - mongodb1_data_container:/data/db
    networks:
      - mongo_cluster

  # Шард 2
  mongodb2:
    container_name: mongodb2
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    ports:
      - "27019:27019"
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    volumes:
      - mongodb2_data_container:/data/db
    networks:
      - mongo_cluster

  # Query Router (mongos)
  query_router:
    container_name: query_router
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    depends_on:
      - config_server
    ports:
      - "27020:27020"
    command:
      [
        "mongos",
        "--configdb",
        "config_server/config_server:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
    networks:
      - mongo_cluster

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - query_router
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://query_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - mongo_cluster

volumes:
  mongodb1_data_container:
  mongodb2_data_container:
  config_server_data:

networks:
  mongo_cluster:
    driver: bridge